name: Testing
on: [push]

jobs:
    # Label of the runner job
    runner-job:
        # You must use a Linux environment when using service containers or container jobs
        runs-on: ubuntu-latest

        steps:
            # Downloads a copy of the code in your repository before running CI tests
            - name: Check out repository code
              uses: actions/checkout@v2

            - name: Install yarn
              run: sudo npm install -g yarn

            - name: Install dependencies with yarn
              run: yarn install

            - name: Run Test
              run: yarn test

              env:
                  NODE_ENV: test
